const path = require('path');
const { VanillaExtractPlugin } = require('@vanilla-extract/webpack-plugin');
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

module.exports = {
    plugins: [new VanillaExtractPlugin(),new MiniCssExtractPlugin],
    mode: 'development',//or production
    devtool: 'source-map',
    resolve: {
        extensions: ['.ts', '.tsx', '.js'],
    },
    entry: {
        main: path.resolve(__dirname, "./src/index.ts")
    },
    output: {
        filename: "bundle.js",
        path: path.join(__dirname, 'dist'),
    },
    module: {
        rules: [
            {
                test: /\.(ts|js)x?$/,
                exclude: /node_modules/,
                use: 'babel-loader'
            },
            {
                test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
                use: [
                  MiniCssExtractPlugin.loader,
                  {
                    loader: require.resolve('css-loader'),
                    options: {
                      url: false // Required as image imports should be handled via JS/TS import statements
                    }
                  }
                ]
            }
        ]
        
    },
    devServer: {
        static: path.join(__dirname, 'dist'),
        hot: true,
        compress: true,
        allowedHosts:["sgb.st"],
    },
}